name: flutter_easyloading
description: ✨A clean and lightweight loading/toast widget for Flutter, easy to use without context, support iOS、Android and Web
version: 2.2.2
homepage: https://github.com/kokohuang/flutter_easyloading

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_spinkit: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
